const fs = require('fs');

const library = fs.readFileSync('exercise_library_ai.txt', 'utf8');

const doc = [
  '# AI Prompt Reference — Adaptive Workout App',
  '# Exercise Library + Schema for Manual Prompt Testing',
  '# Generated: 2026-04-17',
  '# Exercise count: 136  |  Variants: 7',
  '# =============================================================',
  '# PURPOSE',
  '# This document is the complete AI context for plan generation and modification.',
  '# Use it as a reference when testing prompts manually (e.g. via Claude.ai Pro).',
  '# Paste Section 1 (tag dictionary) and Section 2 (schemas) into your system prompt,',
  '# followed by Section 3 (exercise library). Then provide a user profile or',
  '# modification request as the user message.',
  '# =============================================================',
  '',
  '---',
  '',
  '## SECTION 1 — TAG DICTIONARY',
  '',
  'The exercise library uses terse codes throughout. Meanings are:',
  '',
  '### Field keys (used in terse JSON)',
  '| Key  | Full name              | Type          |',
  '|------|------------------------|---------------|',
  '| id   | exercise ID            | string        |',
  '| n    | name                   | string        |',
  '| mv   | movement pattern       | string[]      |',
  '| pm   | primary muscles        | string[]      |',
  '| sm   | secondary muscles      | string[]      |',
  '| eq   | equipment required     | string[]      |',
  '| bp   | body position          | string[]      |',
  '| js   | joint stress           | string[]      |',
  '| cat  | category               | string[]      |',
  '| pl   | plane of motion        | string[]      |',
  '| ap   | anchor point (bands)   | string[]      |',
  '| d    | difficulty             | 1–5 int       |',
  '| cx   | complexity             | 1–5 int       |',
  '| hr   | HR impact              | 1–5 int       |',
  '| so   | space overhead         | 1–3 int       |',
  '| sh   | space horizontal       | 1–3 int       |',
  '| gd   | grip demand            | 1–3 int       |',
  '| nl   | noise level            | 1–3 int       |',
  '| st   | default step type      | "timed"/"rep" |',
  '| dr   | typical duration range | [min,max]s    |',
  '| rr   | typical rep range      | [min,max]     |',
  '| uni  | is unilateral          | bool          |',
  '| cmp  | is compound            | bool          |',
  '| jmp  | has jumping            | bool          |',
  '| stl  | stretch loaded         | bool          |',
  '| wt   | weightable             | bool          |',
  '| sub  | substitutes            | name[]        |',
  '| prog | progressions (harder)  | name[]        |',
  '| reg  | regressions (easier)   | name[]        |',
  '| var  | variants               | name[]        |',
  '',
  '### Movement pattern codes',
  'push_h, push_v, pull_h, pull_v, hinge, squat, lunge, carry, rotation, iso, plyo, gait',
  '',
  '### Muscle group codes',
  'chest, lats, upper_back, traps, rhomboids,',
  'delt_a (anterior deltoid), delt_l (lateral deltoid), delt_p (posterior deltoid),',
  'biceps, triceps, forearms,',
  'core, obliques, erectors,',
  'glutes, quads, hams, calves,',
  'hip_flex, adductors, abductors',
  '',
  '### Equipment codes',
  'bw (bodyweight), db (dumbbell), kb (kettlebell), bb (barbell), cb (curl bar),',
  'band (resistance band), trx, bench, pullup (pull-up bar), cable, ball, roller, mat',
  '',
  '### Body position codes',
  'stand, sit, kneel, prone, supine, lateral, hang, quadruped',
  '',
  '### Joint stress codes',
  'knee, shoulder, wrist, lback (lower back), ankle, hip, elbow, neck',
  '',
  '### Category codes',
  'str (strength), mob (mobility), stretch, warmup, plyo (plyometric), balance, stab (stability)',
  '',
  '### Plane of motion codes',
  'sag (sagittal), front (frontal), trans (transverse)',
  '',
  '### Anchor point codes (resistance bands only)',
  'anchor_none (held/looped, no fixed anchor), anchor_low (door bottom / floor level),',
  'anchor_mid (waist height), anchor_high (overhead), anchor_foot (stepped on), anchor_door (door frame)',
  '',
  '### Numeric scales',
  '- d (difficulty): 1=very easy → 5=very hard',
  '- cx (complexity): 1=simple → 5=high skill/coordination demand (independent of difficulty)',
  '- hr (HR impact): 1=significantly lowers HR, 3=neutral/maintains, 5=significantly raises HR',
  '- so (space overhead): 1=none/seated, 2=arms raised above head, 3=jumping or full overhead press',
  '- sh (space horizontal): 1=stationary footprint, 2=small area shift, 3=lunges/sprawls/crawls',
  '- gd (grip demand): 1=no grip, 2=moderate grip, 3=grip-intensive',
  '- nl (noise level): 1=silent, 2=moderate, 3=loud/impact',
  '',
  '---',
  '',
  '## SECTION 2 — AI INPUT / OUTPUT SCHEMAS',
  '',
  '### generatePlan — Input',
  '',
  '```typescript',
  'interface GeneratePlanInput {',
  '  schemaVersion: number;',
  '  userProfile: {',
  '    primaryGoal: "general_fitness" | "strength" | "hypertrophy" | "weight_loss" | "rehabilitation";',
  '    equipment: string[];               // equipment codes from tag dictionary, e.g. ["band","bw","trx"]',
  '    sessionsPerWeek: number;',
  '    targetDuration: "20-30" | "30-45" | "45-60" | "60+";',
  '    fitnessLevel: "beginner" | "intermediate" | "experienced";',
  '    limitations: string;               // injuries / movements to avoid (free-form)',
  '    additionalContext: string | null;  // any other relevant preferences',
  '  };',
  '  recentFeedback: Array<{',
  '    completedAt: string;               // ISO 8601',
  '    isComplete: boolean;',
  '    commentText: string | null;',
  '  }>;',
  '  // exerciseLibrary is provided in Section 3 below',
  '}',
  '```',
  '',
  '### generatePlan — Output',
  '',
  '```typescript',
  'interface GeneratePlanOutput {',
  '  schemaVersion: number;',
  '  plan: {',
  '    name: string;',
  '    description: string;',
  '    config: {',
  '      defaultWorkSec: number;',
  '      restBetweenExSec: number;',
  '      stretchBetweenRoundsSec: number;  // total time budget: stretch + rest combined',
  '      restBetweenRoundsSec: number;     // remaining rest after stretch; skip if < 5s',
  '      warmupDelayBetweenItemsSec: number;   // auto-pause between warmup items; default 5',
  '      cooldownDelayBetweenItemsSec: number; // auto-pause between cooldown items',
  '    };',
  '  };',
  '  sessions: Array<{',
  '    name: string;',
  '    type: "resistance" | "mobility" | "stretching";',
  '    orderInPlan: number;',
  '    rounds: number;',
  '    estimatedDurationMinutes: number;  // pre-calculate accurately; see duration notes below',
  '    workSec: number;',
  '    restBetweenExSec: number;',
  '    stretchBetweenRoundsSec: number;',
  '    restBetweenRoundsSec: number;',
  '    warmupDelayBetweenItemsSec: number;',
  '    cooldownDelayBetweenItemsSec: number;',
  '    betweenRoundExercise: ExerciseDraft | null;  // phase must be null; typically a stretch',
  '    exercises: ExerciseDraft[];',
  '  }>;',
  '}',
  '',
  'interface ExerciseDraft {',
  '  phase: "warmup" | "main" | "cooldown" | null;  // null = betweenRoundExercise only',
  '  order: number;           // execution order within phase; ignored for phase: null',
  '  exerciseId: string;      // MUST be an id present in the exerciseLibrary',
  '  type: "timed" | "rep";',
  '  durationSec: number | null;   // null if type="rep"; per-side if isBilateral=true',
  '  reps: number | null;          // null if type="timed"; per-side if isBilateral=true',
  '  isBilateral: boolean;',
  '}',
  '```',
  '',
  '### modifyPlan — Input',
  '',
  '```typescript',
  'interface ModifyPlanInput {',
  '  schemaVersion: number;',
  '  currentPlan: { name: string; description: string; config: PlanConfig; };',
  '  currentSessions: Session[];          // sessions as stored',
  '  currentExercises: Exercise[];        // exercise records from session store',
  '  contextRecord: string;               // plain-text AI-maintained preference record',
  '  recentFeedback: SessionFeedback[];   // post-session comments; may be empty',
  '  conversation: Array<{ role: "user" | "assistant"; content: string }>;',
  '  // exerciseLibrary is provided in Section 3 below',
  '}',
  '```',
  '',
  '### modifyPlan — Output',
  '',
  '```typescript',
  'interface ModifyPlanOutput {',
  '  schemaVersion: number;',
  '  summary: string;                     // plain-language rationale shown to user before/after preview',
  '  planChanges: Partial<PlanDraft> | null;',
  '  sessionChanges: Array<{',
  '    sessionId: string | null;          // null = new session being added',
  '    action: "update" | "add" | "remove";',
  '    sessionDraft: Partial<SessionDraft> | null;   // null if action="remove"',
  '    exerciseChanges: Array<{',
  '      exerciseId: string | null;       // null = new exercise being added',
  '      action: "update" | "add" | "remove";',
  '      exerciseDraft: Partial<ExerciseDraft> | null;  // null if action="remove"',
  '    }>;',
  '  }>;',
  '  contextRecordUpdate: string | null;  // FULL replacement text for context record (not delta); null if no change needed',
  '}',
  '```',
  '',
  '### Duration estimation notes',
  'The runtime executes sessions in this fixed order:',
  '1. Warmup — sequential items, each timed or rep-based, with warmupDelayBetweenItemsSec auto-pause between items',
  '2. Main circuit x N rounds:',
  '   a. Each exercise: workSec (or user-paced for reps)',
  '   b. restBetweenExSec between exercises',
  '   c. End of each round (except final): stretchBetweenRoundsSec (includes stretch + rest)',
  '3. Cooldown — sequential timed stretches with cooldownDelayBetweenItemsSec auto-pause between items',
  '',
  'For bilateral timed exercises (uni=true, type="timed"): runtime splits into Left + Right;',
  'durationSec is per-side. Total time = durationSec * 2. Account for this in estimatedDurationMinutes.',
  '',
  '### Hard constraints (algorithmic — always enforced)',
  '- exerciseId MUST be an id present in the exerciseLibrary provided. Unknown IDs are validation failures.',
  '- eq[] tags of selected exercises must be a subset of userProfile.equipment.',
  '- js[] (joint stress) of selected exercises must not conflict with userProfile.limitations.',
  '- contextRecordUpdate is full replacement content, not a delta.',
  '',
  '---',
  '',
  '## SECTION 3 — EXERCISE LIBRARY (136 exercises)',
  '',
  'One exercise per line. Each line is compact JSON.',
  'Field key meanings are in Section 1.',
  'The AI must only reference id values present in this list.',
  '',
  '```',
  library,
  '```',
].join('\n');

fs.writeFileSync('docs/ai-prompt-reference.md', doc);
console.log('Written docs/ai-prompt-reference.md —', doc.length, 'chars //', Math.round(doc.length/4), 'approx tokens');
