-- Batch 07: Lunge / Single-Leg (new)
-- Split Squat, Forward Lunge, Banded Reverse Lunge, Lateral Lunge, Curtsy Lunge,
-- Walking Lunge, Bulgarian Split Squat, Banded Bulgarian Split Squat, Step-Up, Single-Leg Romanian Deadlift

INSERT INTO exercise_definition (
  id, name, aliases, instructions, form_cues, youtube_search_query,
  media_url, media_thumbnail_url,
  movement, primary_muscles, secondary_muscles, equipment, body_position,
  joint_stress, category, plane, anchor_point,
  difficulty, complexity, hr_impact, space_overhead, space_horizontal,
  grip_demand, noise_level,
  default_step_type, typical_duration_range, typical_rep_range,
  is_unilateral, is_compound, has_jumping, stretch_loaded, weightable,
  substitutes, progressions, regressions,
  created_at, updated_at
) VALUES

(
  'ed-051', 'Split Squat',
  '["Static Lunge"]',
  '["Stand in a staggered stance with one foot forward and one foot back, about two feet apart","Lower your body by bending both knees until the back knee hovers just above the floor","Front knee stays over the ankle, torso remains upright","Press through the front heel to return to the starting position"]',
  '["Front knee over ankle","Back knee hovers just above floor","Torso upright throughout"]',
  'split squat proper form',
  NULL, NULL,
  '["lunge"]', '["quads","glutes"]', '["hams","core","adductors"]',
  '["bw"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["sag"]', '[]',
  1, 1, 3, 2, 2, 1, 1,
  'rep', NULL, '[8,15]',
  1, 1, 0, 1, 1,
  '["Reverse Lunge","Forward Lunge"]',
  '["Reverse Lunge","Bulgarian Split Squat"]',
  '["Bodyweight Squat"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-052', 'Forward Lunge',
  '["Front Lunge"]',
  '["Stand with feet hip-width apart","Step one foot forward and lower until both knees form approximately 90-degree angles","Front knee stays over the ankle, back knee hovers just above the floor","Push through the front heel to return to the starting position"]',
  '["Front knee over ankle","Controlled step forward","Drive back through the front heel"]',
  'forward lunge proper form',
  NULL, NULL,
  '["lunge"]', '["quads","glutes"]', '["hams","core","adductors"]',
  '["bw"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["sag"]', '[]',
  2, 2, 4, 2, 2, 1, 1,
  'rep', NULL, '[8,12]',
  1, 1, 0, 1, 1,
  '["Reverse Lunge","Split Squat"]',
  '["Walking Lunge"]',
  '["Reverse Lunge","Split Squat"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-053', 'Banded Reverse Lunge',
  '["Resistance Band Reverse Lunge"]',
  '["Stand on a resistance band with both feet, holding the ends at shoulder height","Step one foot back and lower until both knees form approximately 90-degree angles","Press through the front heel to return to standing against band resistance","Complete all reps on one side or alternate"]',
  '["Front knee over ankle","Band adds resistance at the top","Torso upright"]',
  'resistance band reverse lunge form',
  NULL, NULL,
  '["lunge"]', '["quads","glutes"]', '["hams","core","adductors"]',
  '["band","bw"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["sag"]', '["anchor_foot"]',
  3, 2, 4, 2, 2, 2, 1,
  'rep', NULL, '[8,12]',
  1, 1, 0, 1, 0,
  '["Reverse Lunge","Banded Squat"]',
  '["Banded Bulgarian Split Squat"]',
  '["Reverse Lunge"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-054', 'Lateral Lunge',
  '["Side Lunge"]',
  '["Stand with feet together","Take a wide step to one side, pushing hips back and bending the stepping knee","Keep the trailing leg straight with foot flat on the floor","Push through the bent leg to return to the starting position"]',
  '["Hips push back — like a single-leg squat","Trailing leg stays straight","Chest stays up"]',
  'lateral lunge proper form',
  NULL, NULL,
  '["lunge"]', '["quads","glutes","adductors"]', '["hams","core","abductors"]',
  '["bw"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["front","sag"]', '[]',
  2, 2, 3, 2, 3, 1, 1,
  'rep', NULL, '[8,12]',
  1, 1, 0, 1, 1,
  '["Cossack Squat","Reverse Lunge"]',
  '["Cossack Squat"]',
  '["Sumo Squat","Reverse Lunge"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-055', 'Curtsy Lunge',
  '["Crossover Lunge"]',
  '["Stand with feet hip-width apart","Step one foot back and across behind the other leg, as if curtsying","Lower until the front thigh is roughly parallel to the floor","Press through the front heel to return to standing"]',
  '["Front knee tracks over toes — don''t let it cave in","Torso stays upright","Controlled crossover step"]',
  'curtsy lunge proper form',
  NULL, NULL,
  '["lunge"]', '["glutes","quads","adductors"]', '["core","abductors","hams"]',
  '["bw"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["front","sag"]', '[]',
  2, 2, 3, 2, 2, 1, 1,
  'rep', NULL, '[8,12]',
  1, 1, 0, 0, 1,
  '["Reverse Lunge","Lateral Lunge"]',
  '[]',
  '["Reverse Lunge"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-056', 'Walking Lunge',
  '[]',
  '["Stand with feet hip-width apart with space to walk forward","Step forward into a lunge, lowering until both knees are at approximately 90 degrees","Push through the front heel and step the back foot forward into the next lunge","Continue alternating legs as you walk forward"]',
  '["Front knee over ankle each step","Smooth transitions between steps","Torso upright — don''t lean forward"]',
  'walking lunge proper form',
  NULL, NULL,
  '["lunge"]', '["quads","glutes"]', '["hams","core","adductors"]',
  '["bw"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["sag"]', '[]',
  2, 2, 4, 2, 3, 1, 1,
  'rep', NULL, '[8,12]',
  1, 1, 0, 1, 1,
  '["Forward Lunge","Reverse Lunge"]',
  '["Bulgarian Split Squat"]',
  '["Reverse Lunge","Forward Lunge"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-057', 'Bulgarian Split Squat',
  '["Rear-Foot-Elevated Split Squat","RFESS"]',
  '["Stand about two feet in front of a bench or elevated surface","Place the top of your rear foot on the bench behind you","Lower your body by bending the front knee until the back knee nearly touches the floor","Press through the front heel to return to standing"]',
  '["Front knee over ankle","Torso upright or slight forward lean","Most weight in the front leg"]',
  'bulgarian split squat proper form',
  NULL, NULL,
  '["lunge"]', '["quads","glutes"]', '["hams","core","adductors","hip_flex"]',
  '["bw","bench"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["sag"]', '[]',
  3, 2, 4, 2, 2, 1, 1,
  'rep', NULL, '[6,12]',
  1, 1, 0, 1, 1,
  '["Reverse Lunge","Split Squat"]',
  '["Banded Bulgarian Split Squat","Pistol Squat"]',
  '["Reverse Lunge","Split Squat"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-058', 'Banded Bulgarian Split Squat',
  '["Resistance Band Bulgarian Split Squat"]',
  '["Stand on a resistance band with your front foot, holding the ends at shoulder height","Place the top of your rear foot on a bench behind you","Lower your body by bending the front knee until the back knee nearly touches the floor","Press through the front heel against band resistance to return to standing"]',
  '["Front knee over ankle","Band adds resistance at the top","Control the descent"]',
  'banded bulgarian split squat form',
  NULL, NULL,
  '["lunge"]', '["quads","glutes"]', '["hams","core","adductors","hip_flex"]',
  '["band","bw","bench"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["sag"]', '["anchor_foot"]',
  4, 2, 4, 2, 2, 2, 1,
  'rep', NULL, '[6,10]',
  1, 1, 0, 1, 0,
  '["Bulgarian Split Squat","Banded Reverse Lunge"]',
  '["Pistol Squat"]',
  '["Bulgarian Split Squat","Banded Reverse Lunge"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-059', 'Step-Up',
  '["Box Step-Up"]',
  '["Stand facing a bench or sturdy elevated surface","Place one foot entirely on the surface","Drive through the top foot to step up until the leg is fully extended","Lower yourself back down with control, keeping the working leg engaged"]',
  '["Drive through the top foot — don''t push off the bottom foot","Full extension at the top","Control the descent"]',
  'step up exercise proper form',
  NULL, NULL,
  '["lunge"]', '["quads","glutes"]', '["hams","core","calves"]',
  '["bw","bench"]', '["stand"]', '["knee","hip"]',
  '["str"]', '["sag"]', '[]',
  2, 1, 3, 2, 1, 1, 1,
  'rep', NULL, '[8,15]',
  1, 1, 0, 0, 1,
  '["Reverse Lunge","Bulgarian Split Squat"]',
  '["Bulgarian Split Squat"]',
  '["Reverse Lunge","Split Squat"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-060', 'Single-Leg Romanian Deadlift',
  '["Single-Leg RDL","SLRDL"]',
  '["Stand on one leg with a slight bend in the knee","Hinge at the hips, extending the free leg straight behind you for counterbalance","Lower your torso until you feel a stretch in the standing leg''s hamstring","Drive hips forward to return to standing, squeezing the glute at the top"]',
  '["Flat back throughout","Hips stay square — don''t rotate open","Free leg extends in line with torso"]',
  'single leg romanian deadlift bodyweight form',
  NULL, NULL,
  '["hinge","lunge"]', '["hams","glutes"]', '["core","erectors","adductors"]',
  '["bw"]', '["stand"]', '["lback","hip","ankle"]',
  '["str","balance"]', '["sag"]', '[]',
  3, 3, 3, 2, 1, 1, 1,
  'rep', NULL, '[6,12]',
  1, 1, 0, 1, 1,
  '["Banded Romanian Deadlift","Reverse Lunge"]',
  '[]',
  '["Banded Romanian Deadlift","Glute Bridge"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
);
