-- Batch 18: Stretch / Mobility
-- Standing Hamstring Stretch, Kneeling Hip Flexor Stretch, Pigeon Stretch,
-- 90/90 Hip Stretch, Figure-Four Stretch, Butterfly Stretch,
-- Seated Forward Fold, Cat-Cow, Child's Pose, Downward Dog

INSERT INTO exercise_definition (
  id, name, aliases, instructions, form_cues, youtube_search_query,
  media_url, media_thumbnail_url,
  movement, primary_muscles, secondary_muscles, equipment, body_position,
  joint_stress, category, plane, anchor_point,
  difficulty, complexity, hr_impact, space_overhead, space_horizontal,
  grip_demand, noise_level,
  default_step_type, typical_duration_range, typical_rep_range,
  is_unilateral, is_compound, has_jumping, stretch_loaded, weightable,
  substitutes, progressions, regressions,
  created_at, updated_at
) VALUES

(
  'ed-118', 'Standing Hamstring Stretch',
  '["Standing Toe Touch","Forward Fold Standing"]',
  '["Stand with feet hip-width apart","Hinge at the hips and reach your hands toward your toes, keeping your back as flat as possible","Let your head hang relaxed and hold the stretch at the bottom","Return to standing slowly"]',
  '["Hinge from the hips, not the lower back","Slight knee bend is fine","Breathe deeply and relax into the stretch"]',
  'standing hamstring stretch form',
  NULL, NULL,
  '["hinge"]', '["hams"]', '["calves","erectors","glutes"]',
  '["bw"]', '["stand"]', '["lback"]',
  '["stretch"]', '["sag"]', '[]',
  1, 1, 1, 1, 1, 1, 1,
  'timed', '[20,45]', NULL,
  0, 0, 0, 1, 0,
  '["Seated Forward Fold","Standing Quad Stretch"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-119', 'Kneeling Hip Flexor Stretch',
  '["Half-Kneeling Hip Flexor Stretch","Lunge Stretch"]',
  '["Kneel on one knee with the other foot flat on the floor in front of you, both knees at 90 degrees","Shift your hips forward while keeping your torso tall","You should feel a deep stretch in the front of the hip on the kneeling leg","Hold, then switch sides"]',
  '["Squeeze the glute on the kneeling side","Torso stays upright — don''t lean forward","Gentle forward shift, not a lunge"]',
  'kneeling hip flexor stretch form',
  NULL, NULL,
  '["lunge"]', '["hip_flex"]', '["quads","glutes"]',
  '["bw","mat"]', '["kneel"]', '["knee"]',
  '["stretch"]', '["sag"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'timed', '[20,45]', NULL,
  1, 0, 0, 1, 0,
  '["Pigeon Stretch","90/90 Hip Stretch"]',
  '["Pigeon Stretch"]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-120', 'Pigeon Stretch',
  '["Pigeon Pose","Sleeping Pigeon"]',
  '["From a plank or all-fours position, bring one knee forward and place it behind the same-side wrist","Extend the back leg straight behind you with the top of the foot on the floor","Sink your hips toward the floor, keeping them square","Hold the stretch; for a deeper stretch, fold your torso forward over the front leg"]',
  '["Keep hips square to the floor","Front shin can be angled — it doesn''t need to be parallel","Ease into depth gradually"]',
  'pigeon stretch hip opener form',
  NULL, NULL,
  '["iso"]', '["glutes","hip_flex"]', '["adductors","erectors"]',
  '["bw","mat"]', '["prone"]', '["knee","hip"]',
  '["stretch","mob"]', '["sag"]', '[]',
  2, 2, 1, 1, 2, 1, 1,
  'timed', '[30,60]', NULL,
  1, 0, 0, 1, 0,
  '["90/90 Hip Stretch","Figure-Four Stretch"]',
  '[]',
  '["Figure-Four Stretch","Kneeling Hip Flexor Stretch"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-121', '90/90 Hip Stretch',
  '["90/90 Stretch","90/90 Hip Switch"]',
  '["Sit on the floor with one leg bent in front of you at 90 degrees and the other leg bent behind you at 90 degrees","Sit tall with your torso upright, stacking your spine","Hold the position, feeling the stretch in both hips","To increase intensity, lean your torso forward over the front shin"]',
  '["Both knees at 90-degree angles","Sit tall — don''t round the back","Switch sides for both hips"]',
  '90/90 hip stretch mobility form',
  NULL, NULL,
  '["iso"]', '["glutes","hip_flex"]', '["adductors","abductors"]',
  '["bw","mat"]', '["sit"]', '["hip","knee"]',
  '["stretch","mob"]', '["trans"]', '[]',
  2, 2, 1, 1, 2, 1, 1,
  'timed', '[30,60]', NULL,
  1, 0, 0, 1, 0,
  '["Pigeon Stretch","Figure-Four Stretch"]',
  '[]',
  '["Figure-Four Stretch"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-122', 'Figure-Four Stretch',
  '["Supine Figure Four","Supine Pigeon"]',
  '["Lie on your back with both knees bent and feet flat on the floor","Cross one ankle over the opposite knee, forming a figure-four shape","Reach through and pull the bottom leg toward your chest","Hold the stretch, feeling it in the outer hip and glute of the crossed leg"]',
  '["Keep head and shoulders relaxed on the floor","Pull gently — don''t force it","Flex the top foot to protect the knee"]',
  'figure four stretch glute form',
  NULL, NULL,
  '["iso"]', '["glutes"]', '["hip_flex","adductors"]',
  '["bw","mat"]', '["supine"]', '["hip","knee"]',
  '["stretch"]', '["sag"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'timed', '[20,45]', NULL,
  1, 0, 0, 1, 0,
  '["Pigeon Stretch","90/90 Hip Stretch"]',
  '["Pigeon Stretch","90/90 Hip Stretch"]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-123', 'Butterfly Stretch',
  '["Seated Butterfly","Groin Stretch"]',
  '["Sit on the floor with the soles of your feet together and knees out to the sides","Hold your feet with both hands and sit tall","Gently press your knees toward the floor using your elbows or leg muscles","Hold the stretch, breathing deeply"]',
  '["Sit tall — don''t round the back","Gentle pressure on the knees","Feet close to the body for a deeper stretch"]',
  'butterfly stretch groin form',
  NULL, NULL,
  '["iso"]', '["adductors","hip_flex"]', '["glutes"]',
  '["bw","mat"]', '["sit"]', '["hip","knee"]',
  '["stretch"]', '["front"]', '[]',
  1, 1, 1, 1, 1, 1, 1,
  'timed', '[20,45]', NULL,
  0, 0, 0, 1, 0,
  '["Seated Forward Fold","Figure-Four Stretch"]',
  '["90/90 Hip Stretch"]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-124', 'Seated Forward Fold',
  '["Seated Toe Touch","Pike Stretch"]',
  '["Sit on the floor with legs extended straight in front of you","Hinge at the hips and reach your hands toward your toes","Keep your back as flat as possible as you fold forward","Hold the stretch at your end range, breathing into it"]',
  '["Hinge from the hips, not the lower back","Reach for toes or shins — wherever you can","Relax your head and neck"]',
  'seated forward fold hamstring stretch',
  NULL, NULL,
  '["hinge"]', '["hams","erectors"]', '["calves","glutes"]',
  '["bw","mat"]', '["sit"]', '["lback"]',
  '["stretch"]', '["sag"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'timed', '[20,45]', NULL,
  0, 0, 0, 1, 0,
  '["Standing Hamstring Stretch"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-125', 'Cat-Cow',
  '["Cat Cow Stretch","Chakravakasana"]',
  '["Start on all fours with hands under shoulders and knees under hips","Inhale and arch your back, dropping your belly toward the floor and lifting your head (cow)","Exhale and round your back toward the ceiling, tucking your chin and pelvis (cat)","Continue alternating between the two positions with your breath"]',
  '["Move with your breath — inhale cow, exhale cat","Full range from arch to round","Movement flows through the entire spine"]',
  'cat cow stretch form',
  NULL, NULL,
  '["iso"]', '["erectors","core"]', '["hip_flex","delt_a"]',
  '["bw","mat"]', '["quadruped"]', '["lback"]',
  '["stretch","mob"]', '["sag"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'rep', NULL, '[8,15]',
  0, 0, 0, 1, 0,
  '["Child''s Pose","Bird Dog"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-126', 'Child''s Pose',
  '["Balasana","Rest Pose"]',
  '["Kneel on the floor with knees wide apart and big toes touching","Sit your hips back onto your heels","Extend your arms forward along the floor and rest your forehead on the mat","Breathe deeply and hold, letting your body relax into the position"]',
  '["Hips sink back toward heels","Arms extended or alongside the body","Breathe deeply and relax"]',
  'child''s pose stretch form',
  NULL, NULL,
  '["iso"]', '["erectors","lats"]', '["delt_a","glutes","hip_flex"]',
  '["bw","mat"]', '["kneel"]', '[]',
  '["stretch"]', '["sag"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'timed', '[20,60]', NULL,
  0, 0, 0, 1, 0,
  '["Cat-Cow","Downward Dog"]',
  '["Downward Dog"]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-127', 'Downward Dog',
  '["Adho Mukha Svanasana","Down Dog"]',
  '["Start on all fours, then lift your hips up and back, straightening your legs","Press your hands firmly into the floor with fingers spread, arms straight","Push your heels toward the floor and let your head hang between your arms","Hold the inverted V position, breathing deeply"]',
  '["Flat back — don''t round the spine","Heels press toward (not necessarily to) the floor","Head hangs naturally between the arms"]',
  'downward dog yoga form',
  NULL, NULL,
  '["iso"]', '["delt_a","hams","calves"]', '["lats","core","erectors","glutes"]',
  '["bw","mat"]', '["prone"]', '["wrist","shoulder"]',
  '["stretch","mob"]', '["sag"]', '[]',
  1, 2, 2, 2, 2, 1, 1,
  'timed', '[20,45]', NULL,
  0, 0, 0, 1, 0,
  '["Child''s Pose","Inchworm"]',
  '[]',
  '["Child''s Pose"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
);
