-- Batch 14: Arms Biceps (new) + Triceps (new)
-- Banded Hammer Curl, Banded Concentration Curl, Banded Reverse Curl, Banded Bayesian Curl,
-- Banded Overhead Tricep Extension, Tricep Dip, Banded Tricep Kickback, Bodyweight Skull Crusher

INSERT INTO exercise_definition (
  id, name, aliases, instructions, form_cues, youtube_search_query,
  media_url, media_thumbnail_url,
  movement, primary_muscles, secondary_muscles, equipment, body_position,
  joint_stress, category, plane, anchor_point,
  difficulty, complexity, hr_impact, space_overhead, space_horizontal,
  grip_demand, noise_level,
  default_step_type, typical_duration_range, typical_rep_range,
  is_unilateral, is_compound, has_jumping, stretch_loaded, weightable,
  substitutes, progressions, regressions,
  created_at, updated_at
) VALUES

(
  'ed-091', 'Banded Hammer Curl',
  '["Band Hammer Curl","Resistance Band Hammer Curl"]',
  '["Stand on a band with feet shoulder-width apart, holding the ends with palms facing each other (neutral grip)","Curl hands toward your shoulders, keeping upper arms stationary and palms facing in","Squeeze at the top, then lower slowly"]',
  '["Palms face each other throughout","Elbows pinned to sides","Full range of motion"]',
  'resistance band hammer curl form',
  NULL, NULL,
  '["pull_v"]', '["biceps","forearms"]', '[]',
  '["band","bw"]', '["stand"]', '["elbow"]',
  '["str"]', '["sag"]', '["anchor_foot"]',
  1, 1, 2, 2, 1, 2, 1,
  'rep', NULL, '[10,20]',
  0, 0, 0, 1, 0,
  '["Banded Bicep Curl","Banded Reverse Curl"]',
  '["Banded Concentration Curl"]',
  '["Banded Bicep Curl"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-092', 'Banded Concentration Curl',
  '["Band Concentration Curl"]',
  '["Sit on a bench or chair, loop one end of the band under your foot on the working side","Hold the other end with the same-side hand, resting your elbow against the inside of your thigh","Curl the band toward your shoulder, squeezing the bicep at the top","Lower slowly with control"]',
  '["Elbow braced against inner thigh","Squeeze hard at the top","Slow eccentric"]',
  'resistance band concentration curl form',
  NULL, NULL,
  '["pull_v"]', '["biceps"]', '["forearms"]',
  '["band"]', '["sit"]', '["elbow"]',
  '["str"]', '["sag"]', '["anchor_foot"]',
  2, 1, 2, 1, 1, 2, 1,
  'rep', NULL, '[10,15]',
  1, 0, 0, 1, 0,
  '["Banded Bicep Curl","Banded Hammer Curl"]',
  '[]',
  '["Banded Bicep Curl"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-093', 'Banded Reverse Curl',
  '["Band Reverse Curl","Resistance Band Reverse Curl"]',
  '["Stand on a band with feet shoulder-width apart, holding the ends with palms facing down (overhand grip)","Curl hands toward your shoulders, keeping upper arms stationary and palms facing down","Squeeze at the top, then lower slowly"]',
  '["Palms face down throughout","Elbows pinned to sides","Controlled tempo"]',
  'resistance band reverse curl form',
  NULL, NULL,
  '["pull_v"]', '["forearms","biceps"]', '[]',
  '["band","bw"]', '["stand"]', '["elbow","wrist"]',
  '["str"]', '["sag"]', '["anchor_foot"]',
  2, 1, 2, 2, 1, 2, 1,
  'rep', NULL, '[12,20]',
  0, 0, 0, 0, 0,
  '["Banded Bicep Curl","Banded Hammer Curl"]',
  '[]',
  '["Banded Bicep Curl"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-094', 'Banded Bayesian Curl',
  '["Band Bayesian Curl"]',
  '["Anchor a band at a low point behind you","Stand facing away from the anchor, holding the band in one hand with arm extended behind your body","Curl the band forward and up by bending at the elbow, keeping your upper arm behind your torso","Lower slowly back to the stretched starting position"]',
  '["Upper arm stays behind the body","Full stretch at the bottom","Squeeze bicep at the top"]',
  'bayesian curl resistance band form',
  NULL, NULL,
  '["pull_v"]', '["biceps"]', '["forearms"]',
  '["band"]', '["stand"]', '["elbow","shoulder"]',
  '["str"]', '["sag"]', '["anchor_low"]',
  2, 2, 2, 2, 1, 2, 1,
  'rep', NULL, '[10,15]',
  1, 0, 0, 1, 0,
  '["Banded Bicep Curl","Banded Concentration Curl"]',
  '[]',
  '["Banded Bicep Curl"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-095', 'Banded Overhead Tricep Extension',
  '["Band Overhead Tricep Extension","Band French Press"]',
  '["Anchor a band at a low point behind you or step on it","Hold the band with both hands behind your head, elbows pointing forward and bent","Extend your arms overhead until fully straight, keeping elbows close to your head","Lower back behind your head with control"]',
  '["Elbows stay close to your head","Full extension at the top","Controlled stretch at the bottom"]',
  'resistance band overhead tricep extension form',
  NULL, NULL,
  '["push_v"]', '["triceps"]', '["delt_a"]',
  '["band"]', '["stand"]', '["elbow","shoulder"]',
  '["str"]', '["sag"]', '["anchor_low","anchor_foot"]',
  2, 1, 2, 3, 1, 2, 1,
  'rep', NULL, '[10,15]',
  0, 0, 0, 1, 0,
  '["Banded Tricep Pushdown","Diamond Push-Up"]',
  '[]',
  '["Banded Tricep Pushdown"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-096', 'Tricep Dip',
  '["Chair Dip","Bench Dip"]',
  '["Sit on the edge of a sturdy chair or bench with hands gripping the edge beside your hips","Slide your hips off the edge, supporting yourself with your arms","Lower your body by bending your elbows to about 90 degrees","Press back up to full arm extension"]',
  '["Elbows point straight back, not out","Stay close to the bench","Don''t drop below 90 degrees at the elbow"]',
  'tricep dip bench form',
  NULL, NULL,
  '["push_v"]', '["triceps"]', '["delt_a","chest"]',
  '["bw","bench"]', '["sit"]', '["elbow","shoulder","wrist"]',
  '["str"]', '["sag"]', '[]',
  2, 1, 3, 1, 1, 1, 1,
  'rep', NULL, '[8,15]',
  0, 1, 0, 1, 1,
  '["Banded Tricep Pushdown","Diamond Push-Up"]',
  '["Diamond Push-Up"]',
  '["Banded Tricep Pushdown"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-097', 'Banded Tricep Kickback',
  '["Band Tricep Kickback","Resistance Band Kickback"]',
  '["Stand on a band with one foot, hinge forward at the hips with a flat back","Hold the band with one hand, upper arm parallel to your torso and elbow bent at 90 degrees","Extend your forearm straight back until the arm is fully straight","Return to the bent position slowly"]',
  '["Upper arm stays parallel to torso throughout","Full extension at the back","Squeeze tricep at lockout"]',
  'resistance band tricep kickback form',
  NULL, NULL,
  '["push_h"]', '["triceps"]', '["delt_p"]',
  '["band"]', '["stand"]', '["elbow"]',
  '["str"]', '["sag"]', '["anchor_foot"]',
  1, 1, 2, 2, 1, 2, 1,
  'rep', NULL, '[12,20]',
  1, 0, 0, 0, 0,
  '["Banded Tricep Pushdown","Banded Overhead Tricep Extension"]',
  '["Banded Overhead Tricep Extension"]',
  '["Banded Tricep Pushdown"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-098', 'Bodyweight Skull Crusher',
  '["Bodyweight Tricep Extension"]',
  '["Stand facing a bench or elevated surface and place both hands on the edge, about shoulder-width apart","Walk your feet back so your body is at an angle, arms extended","Lower your head toward the bench by bending only at the elbows, keeping upper arms stationary","Press back up to full extension by straightening the elbows"]',
  '["Only the elbows bend — shoulders stay fixed","Head goes below or to the level of the hands","Lower surface = harder"]',
  'bodyweight skull crusher tricep form',
  NULL, NULL,
  '["push_h"]', '["triceps"]', '["core","delt_a"]',
  '["bw","bench"]', '["prone"]', '["elbow","wrist"]',
  '["str"]', '["sag"]', '[]',
  3, 2, 2, 1, 2, 1, 1,
  'rep', NULL, '[6,12]',
  0, 0, 0, 1, 0,
  '["Diamond Push-Up","Tricep Dip"]',
  '[]',
  '["Tricep Dip","Banded Tricep Pushdown"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
);
