-- Batch 16: Plyometric
-- Jumping Jack, High Knees, Butt Kicks, Jump Squat, Lunge Jump, Skater Jump, Tuck Jump, Burpee

INSERT INTO exercise_definition (
  id, name, aliases, instructions, form_cues, youtube_search_query,
  media_url, media_thumbnail_url,
  movement, primary_muscles, secondary_muscles, equipment, body_position,
  joint_stress, category, plane, anchor_point,
  difficulty, complexity, hr_impact, space_overhead, space_horizontal,
  grip_demand, noise_level,
  default_step_type, typical_duration_range, typical_rep_range,
  is_unilateral, is_compound, has_jumping, stretch_loaded, weightable,
  substitutes, progressions, regressions,
  created_at, updated_at
) VALUES

(
  'ed-104', 'Jumping Jack',
  '["Star Jump","Side Straddle Hop"]',
  '["Stand with feet together and arms at your sides","Jump your feet out to the sides while simultaneously raising your arms overhead","Jump your feet back together while lowering your arms to your sides","Repeat at a steady rhythm"]',
  '["Land softly on the balls of your feet","Full arm extension overhead","Keep a steady pace"]',
  'jumping jack proper form',
  NULL, NULL,
  '["plyo"]', '["quads","calves"]', '["delt_l","glutes","core"]',
  '["bw"]', '["stand"]', '["knee","ankle"]',
  '["plyo","warmup"]', '["sag","front"]', '[]',
  1, 1, 5, 3, 2, 1, 2,
  'timed', '[20,60]', NULL,
  0, 1, 1, 0, 0,
  '["High Knees","Butt Kicks"]',
  '["Jump Squat"]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-105', 'High Knees',
  '["High Knee Run","Running in Place"]',
  '["Stand with feet hip-width apart, arms at your sides","Drive one knee up toward your chest as high as possible while pumping the opposite arm","Quickly switch legs, driving the other knee up","Continue alternating at a fast pace, staying on the balls of your feet"]',
  '["Knees drive to hip height or above","Stay on the balls of your feet","Pump arms for momentum"]',
  'high knees exercise proper form',
  NULL, NULL,
  '["plyo","gait"]', '["hip_flex","quads","calves"]', '["core","glutes"]',
  '["bw"]', '["stand"]', '["knee","ankle"]',
  '["plyo","warmup"]', '["sag"]', '[]',
  1, 1, 5, 2, 1, 1, 2,
  'timed', '[20,45]', NULL,
  1, 1, 1, 0, 0,
  '["Jumping Jack","Butt Kicks"]',
  '["Jump Squat","Tuck Jump"]',
  '["Butt Kicks"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-106', 'Butt Kicks',
  '["Butt Kickers","Heel Flicks"]',
  '["Stand with feet hip-width apart","Jog in place, kicking your heels up toward your glutes with each step","Keep your thighs relatively stationary — the movement is in the lower leg","Pump your arms naturally as you go"]',
  '["Heels touch or nearly touch your glutes","Stay on the balls of your feet","Quick, light steps"]',
  'butt kicks exercise form',
  NULL, NULL,
  '["plyo","gait"]', '["hams","calves"]', '["hip_flex","glutes"]',
  '["bw"]', '["stand"]', '["knee","ankle"]',
  '["plyo","warmup"]', '["sag"]', '[]',
  1, 1, 4, 2, 1, 1, 2,
  'timed', '[20,45]', NULL,
  1, 0, 1, 0, 0,
  '["High Knees","Jumping Jack"]',
  '["High Knees"]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-107', 'Jump Squat',
  '["Squat Jump","Bodyweight Jump Squat"]',
  '["Stand with feet shoulder-width apart","Lower into a squat until thighs are parallel to the floor","Explode upward, jumping as high as you can","Land softly back into the squat position and immediately repeat"]',
  '["Full squat depth before each jump","Land softly — absorb through knees and hips","Arms swing for momentum"]',
  'jump squat proper form',
  NULL, NULL,
  '["plyo","squat"]', '["quads","glutes","calves"]', '["hams","core"]',
  '["bw"]', '["stand"]', '["knee","ankle"]',
  '["plyo"]', '["sag"]', '[]',
  3, 2, 5, 3, 1, 1, 3,
  'rep', NULL, '[6,15]',
  0, 1, 1, 1, 0,
  '["Lunge Jump","Tuck Jump"]',
  '["Tuck Jump"]',
  '["Bodyweight Squat"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-108', 'Lunge Jump',
  '["Jumping Lunge","Split Jump"]',
  '["Start in a lunge position with one foot forward, both knees bent","Explode upward, switching legs in the air","Land softly in a lunge with the opposite foot forward","Continue alternating without pausing"]',
  '["Land softly and absorb the impact","Switch legs fully in the air","Keep torso upright"]',
  'jumping lunge proper form',
  NULL, NULL,
  '["plyo","lunge"]', '["quads","glutes"]', '["hams","calves","core"]',
  '["bw"]', '["stand"]', '["knee","ankle"]',
  '["plyo"]', '["sag"]', '[]',
  4, 3, 5, 3, 2, 1, 3,
  'rep', NULL, '[6,12]',
  1, 1, 1, 1, 0,
  '["Jump Squat","Tuck Jump"]',
  '["Burpee"]',
  '["Reverse Lunge","Forward Lunge"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-109', 'Skater Jump',
  '["Skater Hop","Lateral Bound"]',
  '["Stand on one leg with a slight bend in the knee","Jump laterally to the opposite side, landing on the other foot","Swing your arms across your body for momentum and balance","Immediately jump back to the starting side and continue alternating"]',
  '["Land softly on one foot","Stay low — keep hips back","Controlled lateral movement"]',
  'skater jump exercise form',
  NULL, NULL,
  '["plyo"]', '["quads","glutes","abductors"]', '["calves","hams","core"]',
  '["bw"]', '["stand"]', '["knee","ankle"]',
  '["plyo"]', '["front"]', '[]',
  3, 2, 5, 2, 3, 1, 2,
  'rep', NULL, '[8,16]',
  1, 1, 1, 0, 0,
  '["Jump Squat","Lunge Jump"]',
  '["Lunge Jump"]',
  '["Lateral Lunge"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-110', 'Tuck Jump',
  '["Knee Tuck Jump"]',
  '["Stand with feet shoulder-width apart","Bend your knees slightly, then explode upward","At the peak of the jump, drive both knees toward your chest","Land softly with knees bent and immediately repeat"]',
  '["Knees come to chest at the top","Land softly — absorb through legs","Reset balance between reps if needed"]',
  'tuck jump exercise form',
  NULL, NULL,
  '["plyo"]', '["quads","hip_flex","calves"]', '["glutes","core"]',
  '["bw"]', '["stand"]', '["knee","ankle"]',
  '["plyo"]', '["sag"]', '[]',
  4, 2, 5, 3, 1, 1, 3,
  'rep', NULL, '[5,10]',
  0, 1, 1, 0, 0,
  '["Jump Squat","Lunge Jump"]',
  '["Burpee"]',
  '["Jump Squat"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-111', 'Burpee',
  '["Squat Thrust"]',
  '["Stand with feet shoulder-width apart","Drop into a squat and place your hands on the floor in front of you","Jump or step your feet back into a plank position","Perform a push-up (optional), then jump or step your feet back to your hands","Explode upward into a jump with arms overhead"]',
  '["Chest touches the floor on the push-up","Full hip extension at the top","Land softly and flow into the next rep"]',
  'burpee proper form',
  NULL, NULL,
  '["plyo"]', '["quads","chest","core"]', '["glutes","hams","triceps","delt_a","calves"]',
  '["bw"]', '["stand"]', '["knee","ankle","wrist","shoulder"]',
  '["plyo"]', '["sag"]', '[]',
  4, 3, 5, 3, 3, 1, 3,
  'rep', NULL, '[5,12]',
  0, 1, 1, 1, 0,
  '["Jump Squat","Mountain Climber"]',
  '[]',
  '["Jump Squat","Mountain Climber"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
);
