-- Batch 19: Stretch / Mobility (cont.)
-- World's Greatest Stretch, Supine Spinal Twist, Thread the Needle,
-- Scorpion Stretch, Chest Doorway Stretch, Cross-Body Shoulder Stretch,
-- Overhead Tricep Stretch, Lat Stretch, Wall Calf Stretch

INSERT INTO exercise_definition (
  id, name, aliases, instructions, form_cues, youtube_search_query,
  media_url, media_thumbnail_url,
  movement, primary_muscles, secondary_muscles, equipment, body_position,
  joint_stress, category, plane, anchor_point,
  difficulty, complexity, hr_impact, space_overhead, space_horizontal,
  grip_demand, noise_level,
  default_step_type, typical_duration_range, typical_rep_range,
  is_unilateral, is_compound, has_jumping, stretch_loaded, weightable,
  substitutes, progressions, regressions,
  created_at, updated_at
) VALUES

(
  'ed-128', 'World''s Greatest Stretch',
  '["WGS","Greatest Stretch"]',
  '["Start in a push-up position and step your right foot up to the outside of your right hand","Drop your left elbow toward the floor inside your right foot, feeling a deep hip stretch","Rotate your right arm up toward the ceiling, opening your chest","Return your hand to the floor, step back to plank, and repeat on the other side"]',
  '["Deep lunge — front knee over ankle","Full thoracic rotation on the reach","Controlled transitions between positions"]',
  'world''s greatest stretch form',
  NULL, NULL,
  '["lunge","rotation"]', '["hip_flex","glutes","obliques"]', '["hams","adductors","core","upper_back"]',
  '["bw","mat"]', '["prone"]', '["hip","knee","shoulder"]',
  '["stretch","mob"]', '["sag","trans"]', '[]',
  2, 3, 3, 1, 3, 1, 1,
  'rep', NULL, '[3,6]',
  1, 1, 0, 1, 0,
  '["Kneeling Hip Flexor Stretch","Pigeon Stretch"]',
  '[]',
  '["Kneeling Hip Flexor Stretch"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-129', 'Supine Spinal Twist',
  '["Lying Spinal Twist","Reclined Twist"]',
  '["Lie on your back with arms extended out to the sides in a T position","Bring one knee up toward your chest, then guide it across your body to the opposite side","Keep both shoulders flat on the floor as the knee drops across","Hold the twist, then switch sides"]',
  '["Both shoulders stay on the floor","Let gravity pull the knee down","Breathe into the stretch"]',
  'supine spinal twist stretch form',
  NULL, NULL,
  '["rotation"]', '["obliques","erectors"]', '["glutes","hip_flex"]',
  '["bw","mat"]', '["supine"]', '["lback"]',
  '["stretch"]', '["trans"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'timed', '[20,45]', NULL,
  1, 0, 0, 1, 0,
  '["Thread the Needle","Scorpion Stretch"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-130', 'Thread the Needle',
  '["Thoracic Rotation Stretch"]',
  '["Start on all fours with hands under shoulders and knees under hips","Reach one arm under your body and through the space between the opposite arm and knee","Let your shoulder and head rest on the floor, feeling the stretch in your upper back","Hold, then return to all fours and repeat on the other side"]',
  '["Reach as far through as possible","Let your head rest on the floor","Feel the stretch in the upper back and shoulder"]',
  'thread the needle stretch form',
  NULL, NULL,
  '["rotation"]', '["upper_back","rhomboids"]', '["delt_p","obliques","lats"]',
  '["bw","mat"]', '["quadruped"]', '["shoulder"]',
  '["stretch","mob"]', '["trans"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'timed', '[20,40]', NULL,
  1, 0, 0, 1, 0,
  '["Supine Spinal Twist","Cat-Cow"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-131', 'Scorpion Stretch',
  '["Prone Spinal Twist","Scorpion Kick Stretch"]',
  '["Lie face down with arms extended out to the sides in a T position","Lift one leg and swing it across your body toward the opposite hand, rotating your hips","Keep both arms and the non-moving leg pressed into the floor","Hold the stretch, then return and switch sides"]',
  '["Arms stay flat on the floor","Controlled leg swing — don''t use momentum","Feel the stretch in the hip flexor and lower back"]',
  'scorpion stretch form',
  NULL, NULL,
  '["rotation"]', '["hip_flex","erectors","obliques"]', '["glutes","core"]',
  '["bw","mat"]', '["prone"]', '["lback","hip"]',
  '["stretch","mob"]', '["trans"]', '[]',
  2, 2, 1, 1, 2, 1, 1,
  'timed', '[20,40]', NULL,
  1, 0, 0, 1, 0,
  '["Supine Spinal Twist","Thread the Needle"]',
  '[]',
  '["Supine Spinal Twist"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-132', 'Chest Doorway Stretch',
  '["Door Frame Chest Stretch","Pec Stretch"]',
  '["Stand in a doorway and place your forearms on each side of the door frame at about 90 degrees","Step one foot forward through the doorway","Lean your body forward until you feel a stretch across your chest and front shoulders","Hold the stretch, breathing deeply"]',
  '["Forearms flat on the frame","Step through gently — don''t force it","Elbows at shoulder height for mid-chest, higher for upper chest"]',
  'chest doorway stretch pec form',
  NULL, NULL,
  '["iso"]', '["chest"]', '["delt_a","biceps"]',
  '["bw"]', '["stand"]', '["shoulder"]',
  '["stretch"]', '["trans"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'timed', '[20,45]', NULL,
  0, 0, 0, 1, 0,
  '["Cross-Body Shoulder Stretch"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-133', 'Cross-Body Shoulder Stretch',
  '["Posterior Shoulder Stretch","Horizontal Arm Stretch"]',
  '["Stand or sit upright","Bring one arm straight across your chest at shoulder height","Use the opposite hand to gently pull the arm closer to your body","Hold the stretch, feeling it in the back of the shoulder; switch sides"]',
  '["Arm stays at shoulder height","Pull gently — don''t force","Keep shoulders down, not shrugged"]',
  'cross body shoulder stretch form',
  NULL, NULL,
  '["iso"]', '["delt_p"]', '["upper_back","rhomboids"]',
  '["bw"]', '["stand"]', '["shoulder"]',
  '["stretch"]', '["trans"]', '[]',
  1, 1, 1, 1, 1, 1, 1,
  'timed', '[20,40]', NULL,
  1, 0, 0, 1, 0,
  '["Chest Doorway Stretch","Overhead Tricep Stretch"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-134', 'Overhead Tricep Stretch',
  '["Tricep Stretch","Behind-the-Head Stretch"]',
  '["Stand or sit upright and raise one arm overhead","Bend the elbow so your hand drops behind your head toward the opposite shoulder blade","Use the opposite hand to gently pull the elbow further behind your head","Hold the stretch, then switch arms"]',
  '["Keep the stretching arm''s elbow pointing straight up","Gentle pull — don''t force","Stand tall, don''t lean to the side"]',
  'overhead tricep stretch form',
  NULL, NULL,
  '["iso"]', '["triceps"]', '["lats","delt_p"]',
  '["bw"]', '["stand"]', '["shoulder","elbow"]',
  '["stretch"]', '["sag"]', '[]',
  1, 1, 1, 2, 1, 1, 1,
  'timed', '[20,40]', NULL,
  1, 0, 0, 1, 0,
  '["Cross-Body Shoulder Stretch","Lat Stretch"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-135', 'Lat Stretch',
  '["Side Reach Stretch","Standing Lat Stretch"]',
  '["Stand with feet shoulder-width apart","Raise one arm overhead and lean your torso to the opposite side","Reach the raised arm over and across, feeling a stretch along the side of your torso and under the arm","Hold, then switch sides"]',
  '["Reach long — don''t just bend sideways","Hips stay centered, don''t shift them","Feel the stretch from hip to fingertips"]',
  'standing lat stretch side reach form',
  NULL, NULL,
  '["iso"]', '["lats"]', '["obliques","erectors"]',
  '["bw"]', '["stand"]', '["shoulder"]',
  '["stretch"]', '["front"]', '[]',
  1, 1, 1, 2, 1, 1, 1,
  'timed', '[20,40]', NULL,
  1, 0, 0, 1, 0,
  '["Overhead Tricep Stretch","Cross-Body Shoulder Stretch"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-136', 'Wall Calf Stretch',
  '["Calf Wall Stretch","Standing Calf Stretch"]',
  '["Stand facing a wall and place both hands on it at chest height","Step one foot back about 2-3 feet, keeping it straight with the heel on the floor","Bend the front knee and lean into the wall until you feel a stretch in the back calf","Hold, then switch legs"]',
  '["Back heel stays flat on the floor","Back leg stays straight","Lean into the wall to increase the stretch"]',
  'wall calf stretch form',
  NULL, NULL,
  '["iso"]', '["calves"]', '["hams"]',
  '["bw"]', '["stand"]', '["ankle"]',
  '["stretch"]', '["sag"]', '[]',
  1, 1, 1, 1, 2, 1, 1,
  'timed', '[20,40]', NULL,
  1, 0, 0, 1, 0,
  '["Standing Hamstring Stretch","Downward Dog"]',
  '[]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
);
