-- Batch 11: Core Flexion
-- Crunch, Reverse Crunch, Bicycle Crunch, Toe Touch, Leg Raise, V-Up, Mountain Climber, Hanging Leg Raise

INSERT INTO exercise_definition (
  id, name, aliases, instructions, form_cues, youtube_search_query,
  media_url, media_thumbnail_url,
  movement, primary_muscles, secondary_muscles, equipment, body_position,
  joint_stress, category, plane, anchor_point,
  difficulty, complexity, hr_impact, space_overhead, space_horizontal,
  grip_demand, noise_level,
  default_step_type, typical_duration_range, typical_rep_range,
  is_unilateral, is_compound, has_jumping, stretch_loaded, weightable,
  substitutes, progressions, regressions,
  created_at, updated_at
) VALUES

(
  'ed-073', 'Crunch',
  '["Basic Crunch","Abdominal Crunch"]',
  '["Lie on your back with knees bent and feet flat on the floor","Place hands behind your head or across your chest","Curl your shoulders off the floor by contracting your abs, lifting about 30 degrees","Lower back down with control"]',
  '["Don''t pull on your neck","Lift with abs, not momentum","Lower back stays on the floor"]',
  'crunch proper form',
  NULL, NULL,
  '["iso"]', '["core"]', '["hip_flex"]',
  '["bw"]', '["supine"]', '["neck"]',
  '["str"]', '["sag"]', '[]',
  1, 1, 2, 1, 1, 1, 1,
  'rep', NULL, '[15,25]',
  0, 0, 0, 0, 0,
  '["Reverse Crunch","Dead Bug"]',
  '["Bicycle Crunch","V-Up"]',
  '[]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-074', 'Reverse Crunch',
  '[]',
  '["Lie on your back with arms at your sides, palms down","Lift your legs with knees bent at 90 degrees","Contract your lower abs to curl your hips off the floor, bringing your knees toward your chest","Lower your hips back to the floor with control"]',
  '["Use abs to lift hips — don''t swing legs","Controlled hip curl","Lower back presses into floor at the start"]',
  'reverse crunch proper form',
  NULL, NULL,
  '["iso"]', '["core"]', '["hip_flex","obliques"]',
  '["bw"]', '["supine"]', '["lback"]',
  '["str"]', '["sag"]', '[]',
  1, 1, 2, 1, 1, 1, 1,
  'rep', NULL, '[12,20]',
  0, 0, 0, 0, 0,
  '["Crunch","Leg Raise"]',
  '["Leg Raise","V-Up"]',
  '["Crunch"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-075', 'Bicycle Crunch',
  '["Bicycle","Alternating Crunch"]',
  '["Lie on your back with hands behind your head and legs lifted, knees bent at 90 degrees","Rotate your torso to bring your right elbow toward your left knee while extending the right leg","Alternate sides in a pedaling motion, bringing the left elbow toward the right knee","Continue alternating with control"]',
  '["Rotate from the torso, not just the elbow","Extend the straight leg fully","Controlled tempo — don''t rush"]',
  'bicycle crunch proper form',
  NULL, NULL,
  '["rotation"]', '["core","obliques"]', '["hip_flex"]',
  '["bw"]', '["supine"]', '["neck","lback"]',
  '["str"]', '["sag","trans"]', '[]',
  2, 2, 3, 1, 1, 1, 1,
  'rep', NULL, '[12,20]',
  1, 0, 0, 0, 0,
  '["Russian Twist","Crunch"]',
  '["V-Up"]',
  '["Crunch","Reverse Crunch"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-076', 'Toe Touch',
  '["Toe Touch Crunch","Vertical Leg Crunch"]',
  '["Lie on your back with legs extended straight up toward the ceiling","Reach your hands up and crunch your shoulders off the floor, reaching for your toes","Touch or reach as close to your toes as possible","Lower shoulders back to the floor with control"]',
  '["Legs stay vertical throughout","Reach with your hands, not just arms","Controlled lower"]',
  'toe touch crunch exercise form',
  NULL, NULL,
  '["iso"]', '["core"]', '["hip_flex"]',
  '["bw"]', '["supine"]', '["neck","lback"]',
  '["str"]', '["sag"]', '[]',
  2, 1, 2, 1, 1, 1, 1,
  'rep', NULL, '[12,20]',
  0, 0, 0, 0, 0,
  '["Crunch","V-Up"]',
  '["V-Up"]',
  '["Crunch"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-077', 'Leg Raise',
  '["Lying Leg Raise","Supine Leg Raise"]',
  '["Lie on your back with legs straight and arms at your sides, palms down","Press your lower back into the floor and lift both legs together toward the ceiling","Raise until legs are perpendicular to the floor or as high as you can while maintaining lower back contact","Lower legs slowly back toward the floor without touching down"]',
  '["Lower back stays pressed into the floor","Legs stay straight","Controlled descent — don''t drop legs"]',
  'lying leg raise proper form',
  NULL, NULL,
  '["iso"]', '["core","hip_flex"]', '["obliques"]',
  '["bw"]', '["supine"]', '["lback"]',
  '["str"]', '["sag"]', '[]',
  2, 1, 3, 1, 1, 1, 1,
  'rep', NULL, '[8,15]',
  0, 0, 0, 0, 0,
  '["Reverse Crunch","Hanging Leg Raise"]',
  '["Hanging Leg Raise","V-Up"]',
  '["Reverse Crunch"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-078', 'V-Up',
  '["V-Sit Up","Jackknife"]',
  '["Lie flat on your back with arms extended overhead and legs straight","Simultaneously lift your legs and torso, reaching your hands toward your feet","Your body should form a V shape at the top of the movement","Lower back down with control to the starting position"]',
  '["Legs and arms meet in the middle","Keep legs as straight as possible","Controlled on the way down"]',
  'v-up exercise proper form',
  NULL, NULL,
  '["iso"]', '["core","hip_flex"]', '["obliques"]',
  '["bw"]', '["supine"]', '["lback"]',
  '["str"]', '["sag"]', '[]',
  3, 2, 3, 1, 2, 1, 1,
  'rep', NULL, '[6,15]',
  0, 0, 0, 0, 0,
  '["Toe Touch","Leg Raise"]',
  '["Hanging Leg Raise"]',
  '["Toe Touch","Crunch"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-079', 'Mountain Climber',
  '["Running Plank"]',
  '["Start in a high plank position on your hands","Drive one knee toward your chest","Quickly switch legs, driving the other knee forward as the first returns","Continue alternating at a controlled or rapid pace"]',
  '["Hips stay level — don''t pike up","Hands stay under shoulders","Core braced throughout"]',
  'mountain climber proper form',
  NULL, NULL,
  '["plyo"]', '["core","hip_flex"]', '["delt_a","quads","glutes"]',
  '["bw"]', '["prone"]', '["wrist","shoulder"]',
  '["str","plyo"]', '["sag"]', '[]',
  2, 2, 5, 1, 1, 1, 2,
  'timed', '[20,45]', NULL,
  1, 1, 0, 0, 0,
  '["Plank","High Knees"]',
  '["Burpee"]',
  '["Plank","Dead Bug"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
),

(
  'ed-080', 'Hanging Leg Raise',
  '["Hanging Knee Raise"]',
  '["Hang from a pull-up bar with arms fully extended and shoulders engaged","Lift your legs together by flexing at the hips, keeping them as straight as possible","Raise until legs are parallel to the floor or higher","Lower slowly back to the starting position without swinging"]',
  '["No swinging — controlled movement only","Engage shoulders to prevent hanging passively","Straight legs for full version, bend knees to regress"]',
  'hanging leg raise proper form',
  NULL, NULL,
  '["iso"]', '["core","hip_flex"]', '["obliques","forearms"]',
  '["pullup"]', '["hang"]', '["shoulder","lback"]',
  '["str"]', '["sag"]', '[]',
  4, 2, 3, 3, 1, 3, 1,
  'rep', NULL, '[6,12]',
  0, 0, 0, 0, 0,
  '["Leg Raise","V-Up"]',
  '[]',
  '["Leg Raise","V-Up"]',
  '2026-04-14T00:00:00Z', '2026-04-14T00:00:00Z'
);
